version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      development-dependencies:
        dependency-type: development
    labels:
      - dependencies
