changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Maintenance
      labels:
        - dependencies
        - documentation
    - title: Other changes
      labels:
        - "*"
